python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedavg  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fednova  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.1 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.01 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 123 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 124 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
python run.py --run-id nn_mom --rounds 1000 -b 32 -li static_2 --dataset femnist --model femnist  --deterministic --client-distribution uniform_16 --manual-seed 125 --global-lr 1.0 --local-lr 0.001 --fl-algorithm fedshuffle  --sum-one  --clip-grad --local-lr-type cifar_1 --server-momentum 0.9 --local-weight-decay 0.0001  --num-workers 0 --cluster --cluster-partition learnlab --cluster-time-limit 900
